basket/urls.py
from django.urls import path
from .views import *


app_name = 'basket'

urlpatterns = [
    path('', basket_view, name='basket'),
    path('basket_add/<int:product_id>/', basket_add, name='basket_add'),
]

main/urls.py
from django.urls import path

from .views import *

app_name = 'main'


urlpatterns = [
    path('', ProductView.as_view(), name='product_main'),
    path('header/', header_view, name='header'),
    path('shop/', ProductListView.as_view(), name='product_list'),
    path('shop/category/<slug:category_slug>', ProductListView.as_view(), name='product_list_by_category'),
    path('shop/<slug:post_slug>/', ProductDetailView.as_view(), name='product_detail')
]

orders/urls.py
from django.urls import path
from .views import order_create

app_name = 'orders'

urlpatterns = [
    path('', order_create, name='order_create'),
    path('done/', order_create, name='order_done')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('account/', include('users.urls')),
    path('basket/', include('basket.urls')),
    path('order/', include('orders.urls')),
    path('payment', include('payment.urls')),
    path('__debug__', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/models.py
from django.db import models
from main.models import Product
from users.models import User



class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    modified_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price

basket/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render

from main.models import Product
from shop.services import get_objects_filter, get_objects
from .models import Basket


@login_required
def basket_view(request):
    user = request.user
    baskets = get_objects_filter(Basket, user=user)
    total_quantity = 0
    total_sum = 0
    for basket in baskets:
        total_quantity += basket.quantity
        total_sum += basket.sum()

    return render(request, 'basket/basket.html', {'sum': total_sum, 'quantity': total_quantity, 'baskets': Basket.objects.filter(user=request.user)})



def basket_add(request, product_id):
    current_page = request.META.get('HTTP_REFERER')
    product = get_objects(Product, id=product_id)
    baskets = get_objects_filter(Basket, user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
        return HttpResponseRedirect(current_page)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
        return HttpResponseRedirect(current_page)

basket/templates/basket/basket.html
{% extends 'main/base.html' %}

{% block title %}Корзина {{ user.username.title }}{% endblock title %}

{% block content %}
    <section class="basket d-flex">
        <div class="basket-title">
            <h2>Корзина покупок</h2>
        </div>
        <div class="basket-cards">
            {% for item in baskets %}
                {% with product=item.product %}
                    <div class="basket-card d-flex">
                        <div class="basket-card-img">
                            <img src="{% if product.image %}{{ product.image.url }}{% endif %}">
                        </div>
                        <div class="basket-card-info">
                            <div class="basket-card-name">
                                <p>{{ product.name }}</p>
                            </div>
                            <div class="basket-card-q">
                                <p>Количество: {{ item.quantity }}</p>
                            </div>
                        </div>
                        <div class="basket-card-price">
                            <p class="price">{{ product.price }}</p>
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}
        </div>
        <div class="total">
            <h5>Общая сумма: {{ sum }} р.</h5>
        </div>
        <div class="basket-buttons d-flex gap-3">
            <a href="/shop" class="basket-btn link">Продолжить покупки</a>
            {% if quantity > 0 %}
                <a href="{% url 'orders:order_create' %}" class="basket-btn link">Оформить заказ</a>
            {% endif %}
        </div>
    </section>
{% endblock content %}