main/urls.py
from django.urls import path

from .views import *

app_name = 'main'


urlpatterns = [
    path('', ProductView.as_view(), name='product_main'),
    path('header/', header_view, name='header'),
    path('shop/', ProductListView.as_view(), name='product_list'),
    path('shop/category/<slug:category_slug>', ProductListView.as_view(), name='product_list_by_category'),
    path('shop/<slug:post_slug>/', ProductDetailView.as_view(), name='product_detail')
]

orders/urls.py
from django.urls import path
from .views import order_create

app_name = 'orders'

urlpatterns = [
    path('', order_create, name='order_create'),
    path('done/', order_create, name='order_done')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('account/', include('users.urls')),
    path('basket/', include('basket.urls')),
    path('order/', include('orders.urls')),
    path('payment', include('payment.urls')),
    path('__debug__', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models

from main.models import Product
from users.models import User


class Order(models.Model):
    STATUS_CHOICES = (
    ('pending', 'В ожидании'),
    ('processing', 'В обработке'),
    ('completed', 'Завершен'),
    ('cancelled', 'Отменен'),
    )

    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.EmailField()
    address = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(default='pending', max_length=20, choices=STATUS_CHOICES)
    yookassa_payment_id = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f'Заказ {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django.forms import ModelForm
from .models import Order


class OrderCreateForm(ModelForm):
    class Meta:
        model = Order
        fields = ['user', 'first_name', 'last_name', 'email', 'address']


    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        if self.request.user.is_authenticated:
            self.initial['first_name'] = self.request.user.first_name
            self.initial['last_name'] = self.request.user.last_name
            self.initial['email'] = self.request.user.email

orders/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages

from shop.services import get_objects_filter
from .models import Order, OrderItem
from .forms import OrderCreateForm
from basket.models import Basket
import logging


logger = logging.getLogger(__name__)


def order_create(request, create_yookassa_payment=None):
    if request.user.is_authenticated:
        baskets = get_objects_filter(Basket, user=request.user)
    else:
        baskets = []

    if request.method == 'POST':
        form = OrderCreateForm(request.POST, request=request)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.save()
            for item in baskets:
                price = item.product.price
                OrderItem.objects.create(order=order, product=item.product, price=price, quantity=item.quantity)
            baskets.delete()
            return redirect('payment:checkout', order_id=order.id)
    else:
        form = OrderCreateForm(request=request)
    return render(request, 'orders/order_create.html', {'form': form, 'baskets': Basket.objects.filter(user=request.user)})

orders/templates/orders/order_create.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} {% endblock title %}

{% block content %}
    <div class="forcreate">
        <div class="profile-order p-4 mb-4 mx-2">
            <h2 class="mb-2">Создание заказа</h2>
            <form action="" method="post" class="order-form">
                {% csrf_token %}
                <div class="col-md-12 mb-3">
                    <label for="id_first_name" class="form-label">Имя</label>
                    <input type="text" class="form-control form-styleprofile" id="id_first_name" name="first_name"
                    placeholder="Ваше имя" value="{{ form.first_name.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_last_name" class="form-label">Фамилия</label>
                    <input type="text" class="form-control form-styleprofile" id="id_last_name" name="last_name"
                    placeholder="Ваша фамилия" value="{{ form.last_name.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_email" class="form-label">Email</label>
                    <input type="text" class="form-control form-styleprofile" id="id_email" name="email"
                    placeholder="Ваша почта" value="{{ form.email.value|default:'' }}" required>
                </div>

                <div class="col-md-12 mb-3">
                    <label for="id_address" class="form-label">Адрес</label>
                    <input type="text" class="form-control form-styleprofile" id="id_address" name="address"
                    placeholder="Ваш адрес" value="{{ form.address.value|default:'' }}" required>
                </div>
                <p><input type="submit" class="order-btn" value="Создать заказ"></p>
                {% csrf_token %}
            </form>
        </div>
        <div class="checkout">
            <h1>Заказ</h1>
            <div class="order-info">
                {% for item in baskets %}
                    <li>
                        {{ item.quantity }} x {{ item.product.name }}
                        <p> {{ item.product.price }} р.</p>
                    </li>
                <strong><p>Общая сумма: {{ item.sum }} р.</p></strong>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

orders/templates/orders/order_done.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}
    {{order.id}} create
{% endblock content %}