basket/urls.py
from django.urls import path
from .views import *


app_name = 'basket'

urlpatterns = [
    path('', basket_view, name='basket'),
    path('basket_add/<int:product_id>/', basket_add, name='basket_add'),
]

main/urls.py
from django.urls import path

from .views import *

app_name = 'main'


urlpatterns = [
    path('', ProductView.as_view(), name='product_main'),
    path('header/', header_view, name='header'),
    path('shop/', ProductListView.as_view(), name='product_list'),
    path('shop/category/<slug:category_slug>', ProductListView.as_view(), name='product_list_by_category'),
    path('shop/<slug:post_slug>/', ProductDetailView.as_view(), name='product_detail')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('account/', include('users.urls')),
    path('basket/', include('basket.urls')),
    path('order/', include('orders.urls')),
    path('payment', include('payment.urls')),
    path('__debug__', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_list_by_category', args=[self.slug])


class Brand(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    brand = models.ForeignKey(Brand, related_name='brand', null=True, blank=True, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=100, unique=100)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, null=True)
    image_min = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, null=True)
    image_left = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, null=True)
    image_right = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, null=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_detail', kwargs={'post_slug': self.slug})

main/views.py
from django.shortcuts import render, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator

from shop.services import get_objects_all
from .models import Category, Product


@method_decorator(cache_page(60 * 60), name='dispatch')
class ProductView(ListView):
    model = Product
    template_name = "main/index/index.html"
    context_object_name = "products"


@method_decorator(cache_page(60 * 10), name='dispatch')
class ProductListView(ListView):
    model = Category
    template_name = "main/product/list.html"


    def get(self, request, category_slug=None):
        page = request.GET.get('page', 1)
        category = None
        products = get_objects_all(Product)
        categories = get_objects_all(Category)
        paginator = Paginator(products, 6)
        current_page = paginator.page(int(page))
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            paginator = Paginator(products.filter(category=category), 6)
            current_page = paginator.page(int(page))
        return render(request, 'main/product/list.html',
                      {'category': category, 'products': current_page, 'categories': categories, 'slug': category_slug})


@method_decorator(cache_page(60 * 60 ), name='dispatch')
class ProductDetailView(DetailView):
    model = Product
    template_name = "main/product/detail.html"
    slug_url_kwarg = "post_slug"
    context_object_name = "products"


def header_view(request):
    return render(request, "includes/header.html")

main/templates/main/product/detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}{{ products.name }}{% endblock title %}

{% block content %}
    <div class="detail-container">
        <div class="detail-header">
            <h1 class="product-title">{{ products.name }}</h1>
            {% if products.brand %}
                <p class="brand">{{ products.brand }}</p>
            {% endif %}
        <div class="main-detail">
            <div class="d-flex">
                <img src="{{ products.image.url }}" alt="{{ products.name }}" class="main-photo" />
                {% if products.image_min %}
                    <img src="{{ products.image_min.url }}" alt="{{ products.name }}" class="min-photo" />
                {% endif %}
                <div class="detail-image d-flex">
                    {% if products.image_left and products.image_right %}
                    <img src="{{ products.image_left.url }}" alt="Упаковка" class="left-photo"/>
                    <img src="{{ products.image_right.url }}" alt="На столике" class="right"/>
                    <p>Варианты упаковки</p>
                    {% endif %}
                    <a href="{% url 'basket:basket_add' products.id %}">
                    <button class="btn" type="submit">Добавить в корзину</button>
                    </a>
                </div>
                    <p class="main-detail-disc-tag">Описание</p>
                    <p class="main-detail-disc">{{ products.description }}</p>
            </div>
        </div>
        </div>
    </div>
{% endblock content %}

main/templates/main/product/list.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Магазин{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="catalog-title">Коллекция ароматов</h1>
    <div class="">
        <div class="container-cat">
            <h4 class="pol">Пол</h4>
            {% for item in categories %}
            <ul class="cat nav-links mt-3">
                <li {% if not category %} class="selected"{% endif %}>
                    <a href="{% url 'main:product_list' %}" class="link link-color"></a>
                </li>
                <li {% if category.slug == item.slug %} class="selected"{% endif %}>
                    <a href="{{ item.get_absolute_url }}" class="link link-color">{{ item.name }}</a>
                </li>
            </ul>
        {% endfor %}
        </div>
        <div class="container-product  filters">
            {% for product in products %}
                <div class="list-grid">
                    <a href="{{ product.get_absolute_url }}" class="list-card d-flex flex-column  link align-items-center text-center">
                        <img src="{{ product.image.url }}" class="card-img" alt="{{ product.name }}">
                        <h2>{{ product.name }}</h2>
                        {% if product.brand %}
                            <p class="brand">{{ product.brand }}</p>
                        {% endif %}
                        <p class="price"> {{ product.price }} р.</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main/product/main.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Главная страница{% endblock title %}

{% block content %}
    <div class="container">
        <h2>Хиты продаж</h2>
            <div class="items">
                {% for product in products %}

                {% endfor %}
            </div>
    </div>

    <div class="container">
        <h2>Новые товары</h2>
            <div class="items">
                {% for product in products %}
                    <div class="">
                        <a href="#" class="list-card d-flex flex-column align-items-center text-center">
                            <img src="{{ product.image.url }}" class="card-img" alt="{{ product.name }}">
                            <h5 class="title-card">{{ product.name }}</h5>
                                    <p class="line"> {{ product.price }} р.</p>
                        </a>
                    </div>
                {% endfor %}
            </div>
    </div>
{% endblock content %}