main/urls.py
from django.urls import path

from .views import *

app_name = 'main'


urlpatterns = [
    path('', ProductView.as_view(), name='product_main'),
    path('header/', header_view, name='header'),
    path('shop/', ProductListView.as_view(), name='product_list'),
    path('shop/category/<slug:category_slug>', ProductListView.as_view(), name='product_list_by_category'),
    path('shop/<slug:post_slug>/', ProductDetailView.as_view(), name='product_detail')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('account/', include('users.urls')),
    path('basket/', include('basket.urls')),
    path('order/', include('orders.urls')),
    path('payment', include('payment.urls')),
    path('__debug__', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_list_by_category', args=[self.slug])


class Brand(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    brand = models.ForeignKey(Brand, related_name='brand', null=True, blank=True, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=100, unique=100)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, null=True)
    image_min = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, null=True)
    image_left = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, null=True)
    image_right = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, null=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_detail', kwargs={'post_slug': self.slug})

main/views.py
from django.shortcuts import render, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator

from shop.services import get_objects_all
from .models import Category, Product


@method_decorator(cache_page(60 * 60), name='dispatch')
class ProductView(ListView):
    model = Product
    template_name = "main/index/index.html"
    context_object_name = "products"


@method_decorator(cache_page(60 * 10), name='dispatch')
class ProductListView(ListView):
    model = Category
    template_name = "main/product/list.html"


    def get(self, request, category_slug=None):
        page = request.GET.get('page', 1)
        category = None
        products = get_objects_all(Product)
        categories = get_objects_all(Category)
        paginator = Paginator(products, 6)
        current_page = paginator.page(int(page))
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            paginator = Paginator(products.filter(category=category), 6)
            current_page = paginator.page(int(page))
        return render(request, 'main/product/list.html',
                      {'category': category, 'products': current_page, 'categories': categories, 'slug': category_slug})


@method_decorator(cache_page(60 * 60 ), name='dispatch')
class ProductDetailView(DetailView):
    model = Product
    template_name = "main/product/detail.html"
    slug_url_kwarg = "post_slug"
    context_object_name = "products"


def header_view(request):
    return render(request, "includes/header.html")

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock title %}</title>
    <link rel="shortcut icon" href="{% static 'img/logo.ico' %}" type="image/x-icon"/>

    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

</head>
<body style="background-color: #f9f4ec">
    <div class="main-container">
        <div id="header"></div>
        <script>
            fetch("{% url 'main:header' %}")
              .then(response => response.text())
              .then(html => {
                document.getElementById("header").innerHTML = html;
              });
        </script>
        {% block content %}{% endblock content %}
    </div>
    <footer>
        <div class="footer-content footer-container">
            <div class="footer-logo">
                <p>Магазин изысканных ароматов для тех, кто чувствует стиль.</p>
            </div>
            <div class="footer-social">
                <p>Мы в соцсетях:</p>
                <a href="#">Instagram</a>
                <a href="#">Telegram</a>
                <a href="#">Tik-Tok</a>
            </div>
            <div class="footer-subscribe">
                <p>Подпишитесь на эксклюзивные предложения</p>
                <form>
                    <input type="email" placeholder="Ваш e-mail">
                    <button type="submit">Подписаться</button>
                </form>
            </div>
        </div>
    </footer>
</body>
</html>